export function miniAppHtml() {
  return `<!doctype html>
<html lang="uk">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover" />
<title>Соня · projectseniorservice</title>
<script src="https://telegram.org/js/telegram-web-app.js"></script>
<style>
:root{color-scheme:dark;--bg:#07090d;--panel:#0d121a;--card:#111926;--card2:#141d2b;--text:#ecfdf5;--muted:#8ea0ae;--line:#223043;--accent:#7cffc4;--accent2:#66a6ff;--danger:#ff6b7a;--warn:#ffd166;--ok:#7cffc4;--shadow:0 24px 80px rgba(0,0,0,.45);font-family:Inter,ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,Arial}
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 15% 0,#14382d 0,#07090d 34%),linear-gradient(180deg,#07090d,#090d14);color:var(--text);min-height:100dvh;padding:env(safe-area-inset-top) env(safe-area-inset-right) env(safe-area-inset-bottom) env(safe-area-inset-left)}
.app{max-width:1220px;margin:auto;padding:14px}.top{position:sticky;top:0;z-index:10;background:linear-gradient(180deg,rgba(7,9,13,.96),rgba(7,9,13,.72));backdrop-filter:blur(18px);padding:12px 0 10px}.brand{display:flex;gap:12px;align-items:center;justify-content:space-between}.logo{display:flex;gap:10px;align-items:center}.orb{width:42px;height:42px;border-radius:18px;background:radial-gradient(circle at 30% 25%,#fff,#7cffc4 30%,#174637 65%,#080b10);box-shadow:0 0 34px rgba(124,255,196,.35)}h1{font-size:20px;margin:0}.sub{color:var(--muted);font-size:12px}.pill{border:1px solid var(--line);border-radius:999px;padding:8px 10px;color:var(--muted);font-size:12px;background:rgba(255,255,255,.03)}
.nav{display:flex;gap:8px;overflow:auto;padding:12px 0 2px;scrollbar-width:none}.nav button,.btn{border:1px solid var(--line);background:#0d141f;color:var(--text);border-radius:14px;padding:11px 13px;font-weight:700;cursor:pointer;white-space:nowrap}.nav button.active,.btn.primary{border-color:rgba(124,255,196,.6);background:linear-gradient(135deg,rgba(124,255,196,.18),rgba(102,166,255,.12));box-shadow:0 0 0 1px rgba(124,255,196,.08) inset}.btn.danger{border-color:rgba(255,107,122,.45);color:#ffdce1}.grid{display:grid;grid-template-columns:1.1fr .9fr;gap:14px}.card{background:linear-gradient(180deg,rgba(17,25,38,.92),rgba(13,18,26,.92));border:1px solid var(--line);border-radius:24px;padding:16px;box-shadow:var(--shadow)}.card h2{font-size:16px;margin:0 0 12px}.row{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.stack{display:grid;gap:10px}.item{border:1px solid rgba(255,255,255,.07);background:rgba(255,255,255,.035);border-radius:18px;padding:12px}.item b{display:block;margin-bottom:4px}.meta{color:var(--muted);font-size:12px}.input,textarea,select{width:100%;border:1px solid var(--line);background:#080d14;color:var(--text);border-radius:16px;padding:13px;outline:none}textarea{min-height:96px;resize:vertical}.toast{position:fixed;left:16px;right:16px;bottom:18px;margin:auto;max-width:520px;background:#0f1824;border:1px solid var(--line);border-radius:18px;padding:12px 14px;box-shadow:var(--shadow);display:none}.toast.show{display:block}.empty{color:var(--muted);border:1px dashed var(--line);border-radius:18px;padding:18px;text-align:center}.section{display:none}.section.active{display:block}.kpi{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.kpi div{background:rgba(255,255,255,.04);border:1px solid var(--line);border-radius:18px;padding:12px}.kpi b{font-size:22px}dialog{border:1px solid var(--line);border-radius:26px;background:#0b111a;color:var(--text);box-shadow:var(--shadow);width:min(760px,calc(100vw - 24px));max-height:86dvh}dialog::backdrop{background:rgba(0,0,0,.65);backdrop-filter:blur(8px)}
@media(max-width:820px){.app{padding:10px}.grid{grid-template-columns:1fr}.kpi{grid-template-columns:repeat(2,1fr)}.brand{align-items:flex-start}.card{border-radius:20px;padding:14px}.nav button{padding:10px 12px}.top{top:0}.hide-mobile{display:none}}@media(orientation:landscape) and (max-height:520px){.grid{grid-template-columns:repeat(2,minmax(280px,1fr))}.card{padding:12px}.nav{padding-top:8px}.top{position:relative}}
</style>
</head>
<body>
<div class="app">
  <div class="top">
    <div class="brand"><div class="logo"><div class="orb"></div><div><h1>Соня Family OS</h1><div class="sub">projectseniorservice · private Telegram panel</div></div></div><div class="pill" id="mePill">offline</div></div>
    <div class="nav" id="nav"></div>
  </div>
  <section id="login" class="section active"><div class="card"><h2>Вхід у приватну Соню</h2><p class="sub">Введи Owner або Family access code. Після першого входу сесія збережеться.</p><input id="accessCode" class="input" placeholder="Access code" /><br><br><button class="btn primary" onclick="login()">Увійти</button><button class="btn" onclick="checkSetup()">Перевірити систему</button><button class="btn" onclick="location.href='/admin'">Admin setup</button><div id="loginState" class="meta" style="margin-top:12px"></div></div></section>
  <section id="today" class="section"><div class="grid"><div class="card"><h2>Today / Життєвий inbox</h2><div class="kpi" id="kpis"></div><br><textarea id="quickText" placeholder="Наприклад: Нагадай завтра купити ліки дружині"></textarea><div class="row" style="margin-top:10px"><button class="btn primary" onclick="sendNatural()">Віддати Соні</button><button class="btn" onclick="loadToday()">Оновити</button></div><div id="aiResult" class="item" style="margin-top:12px;display:none"></div></div><div class="card"><h2>Найближче</h2><div id="nextList" class="stack"></div></div></div></section>
  <section id="tasks" class="section"><div class="card"><h2>Tasks / Reminders / Notes</h2><div class="row"><select id="newType"><option value="task">task</option><option value="reminder">reminder</option><option value="note">note</option><option value="contact">contact</option><option value="expense">expense</option><option value="car">car</option><option value="health">health</option><option value="content">content</option><option value="qa">qa</option></select><select id="newVisibility"><option value="private">private</option><option value="shared">shared</option></select></div><br><input class="input" id="newTitle" placeholder="Назва" /><br><br><textarea id="newContent" placeholder="Опис / деталі"></textarea><br><br><button class="btn primary" onclick="createManualItem()">Створити</button></div><br><div class="card"><h2>Усі об’єкти</h2><div id="itemsList" class="stack"></div></div></section>
  <section id="memory" class="section"><div class="card"><h2>Memory Search</h2><input id="searchBox" class="input" placeholder="Знайди все про машину / пошту / задачу дружини" onkeydown="if(event.key==='Enter')search()"/><br><br><button class="btn primary" onclick="search()">Шукати</button><div id="searchResults" class="stack" style="margin-top:12px"></div></div></section>
  <section id="mail" class="section"><div class="grid"><div class="card"><h2>Mail · web-library.net registry</h2><input class="input" id="mailLocal" placeholder="my-name або random"/><br><br><input class="input" id="mailPass" placeholder="password для входу в пошту"/><br><br><button class="btn primary" onclick="createMail()">Створити адресу</button><p class="sub">Відправка назовні не вмикається через web-library.net. Для send потрібен окремий RESEND_API_KEY.</p></div><div class="card"><h2>Адреси</h2><div id="mailList" class="stack"></div></div></div></section>
  <section id="files" class="section"><div class="card"><h2>Files / Documents Safe</h2><input class="input" id="fileTitle" placeholder="Назва документа / чека / гарантії"/><br><br><textarea id="fileDesc" placeholder="Опис, де лежить файл, що це за документ"></textarea><br><br><button class="btn primary" onclick="registerFile()">Зареєструвати</button><div id="filesList" class="stack" style="margin-top:14px"></div></div></section>
  <section id="history" class="section"><div class="card"><h2>Activity History</h2><button class="btn" onclick="loadHistory()">Оновити</button><div id="historyList" class="stack" style="margin-top:12px"></div></div></section>
</div>
<div class="toast" id="toast"></div>
<script>
const tabs=[['today','Today'],['tasks','Tasks'],['memory','Memory'],['mail','Mail'],['files','Files'],['history','History']];
let token=localStorage.sonyaToken||''; let me=null;
function api(path,opt){opt=opt||{};opt.headers=Object.assign({},opt.headers||{}, {'content-type':'application/json'}); if(token)opt.headers.authorization='Bearer '+token; return fetch(path,opt).then(async function(r){const d=await r.json().catch(function(){return {ok:false,error:'Bad JSON'}}); if(!r.ok)throw new Error(d.error||r.statusText); return d;});}
function toast(t){const el=document.getElementById('toast');if(!el)return;el.textContent=t;el.className='toast show';setTimeout(function(){el.className='toast'},2600)}
function nav(){const wrap=document.getElementById('nav');wrap.innerHTML=tabs.map(function(pair){const id=pair[0], label=pair[1];return "<button data-tab='"+esc(id)+"' id='nav_"+esc(id)+"'>"+esc(label)+"</button>"}).join('');wrap.querySelectorAll('[data-tab]').forEach(function(btn){btn.addEventListener('click',function(){show(btn.dataset.tab)})})}
function show(id){document.querySelectorAll('.section').forEach(function(x){x.classList.remove('active')});const sec=document.getElementById(id);if(sec)sec.classList.add('active');document.querySelectorAll('.nav button').forEach(function(x){x.classList.remove('active')});const nb=document.getElementById('nav_'+id);if(nb)nb.classList.add('active'); if(id==='today')loadToday(); if(id==='tasks')loadItems(); if(id==='mail')loadMail(); if(id==='files')loadFiles(); if(id==='history')loadHistory();}
async function boot(){nav(); if(window.Telegram&&Telegram.WebApp){Telegram.WebApp.ready();Telegram.WebApp.expand();} if(token){try{const r=await api('/api/me'); me=r.user; setMePill(me.displayName+' · '+me.role); document.getElementById('login').classList.remove('active');show('today');return;}catch(e){token='';localStorage.removeItem('sonyaToken')}} checkSetup();}
function setMePill(t){const el=document.getElementById('mePill');if(el)el.textContent=t;}
async function checkSetup(){try{const s=await api('/api/setup/status');document.getElementById('loginState').textContent=s.configured?'Система налаштована. Введи access code.':'Система ще не налаштована. Можеш натиснути Admin setup або просто ввести owner2026 — Соня створить перший Owner автоматично.'}catch(e){document.getElementById('loginState').textContent=e.message}}
async function login(){try{const code=document.getElementById('accessCode').value.trim();const r=await api('/api/auth/login',{method:'POST',body:JSON.stringify({accessCode:code,source:'miniapp',publicBaseUrl:location.origin})});token=r.token;localStorage.sonyaToken=token;me=r.user;setMePill(me.displayName+' · '+me.role);toast('Вхід виконано');document.getElementById('login').classList.remove('active');show('today')}catch(e){toast(e.message);const ls=document.getElementById('loginState');if(ls)ls.textContent=e.message}}
async function loadToday(){const r=await api('/api/today');const c=r.data.counts;document.getElementById('kpis').innerHTML='<div><b>'+c.open+'</b><div class="meta">open</div></div><div><b>'+c.today+'</b><div class="meta">today</div></div><div><b>'+c.overdue+'</b><div class="meta">overdue</div></div><div><b>'+c.all+'</b><div class="meta">all</div></div>';document.getElementById('nextList').innerHTML=list(r.data.next.concat(r.data.important).slice(0,12));}
async function sendNatural(){const t=document.getElementById('quickText').value;const r=await api('/api/ai/chat',{method:'POST',body:JSON.stringify({text:t,source:'miniapp'})});document.getElementById('aiResult').style.display='block';document.getElementById('aiResult').textContent=r.result.text;document.getElementById('quickText').value='';loadToday();}
async function createManualItem(){await api('/api/items',{method:'POST',body:JSON.stringify({type:v('newType'),visibility:v('newVisibility'),title:v('newTitle'),content:v('newContent')})});toast('Створено');document.getElementById('newTitle').value='';document.getElementById('newContent').value='';loadItems();}
async function loadItems(){const r=await api('/api/items?limit=160');const target=document.getElementById('itemsList');target.innerHTML=list(r.items,true);bindItemButtons(target);}
async function search(){const r=await api('/api/search?q='+encodeURIComponent(v('searchBox')));const target=document.getElementById('searchResults');target.innerHTML=list(r.results,true);bindItemButtons(target);}
async function createMail(){await api('/api/mail/accounts',{method:'POST',body:JSON.stringify({local:v('mailLocal'),password:v('mailPass')})});toast('Пошта додана');loadMail();}
async function loadMail(){const r=await api('/api/mail/accounts');const box=document.getElementById('mailList');box.innerHTML=r.accounts.length?r.accounts.map(function(a){return '<div class="item"><b>'+esc(a.address)+'</b><div class="meta">'+esc(a.status)+' · '+esc(a.provider)+'</div><button class="btn" data-inbox="'+esc(a.id)+'">Inbox</button></div>'}).join(''):'<div class="empty">Немає адрес</div>';box.querySelectorAll('[data-inbox]').forEach(function(b){b.addEventListener('click',function(){inbox(b.dataset.inbox)})});}
async function inbox(id){const r=await api('/api/mail/accounts/'+encodeURIComponent(id)+'/inbox');toast(r.inbox.note||('Inbox: '+((r.inbox.messages&&r.inbox.messages.length)||0)));}
async function registerFile(){await api('/api/files',{method:'POST',body:JSON.stringify({title:v('fileTitle'),description:v('fileDesc')})});toast('Файл зареєстровано');loadFiles();}
async function loadFiles(){const r=await api('/api/files');document.getElementById('filesList').innerHTML=list(r.files,true);}
async function loadHistory(){const r=await api('/api/admin/activity?limit=80').catch(async function(){const t=await api('/api/today');return {logs:t.data.recent.map(function(x){return {createdAt:x.updatedAt,module:x.type,action:'recent',message:x.title}})}});document.getElementById('historyList').innerHTML=r.logs.length?r.logs.map(function(l){return '<div class="item"><b>'+esc(l.module)+' · '+esc(l.action)+'</b><div class="meta">'+esc(l.createdAt||'')+'</div><div>'+esc(l.message||'')+'</div></div>'}).join(''):'<div class="empty">Поки пусто</div>';}
function list(arr,actions){return arr&&arr.length?arr.map(function(x){return '<div class="item"><b>'+esc(x.title||x.address||x.label||x.id)+'</b><div class="meta">'+esc([x.type,x.visibility,x.status,x.dueAt].filter(Boolean).join(' · '))+'</div><div>'+esc(x.content||x.description||x.note||'')+'</div>'+(actions&&x.id&&x.status!=='done'?'<div class="row" style="margin-top:8px"><button class="btn" data-done="'+esc(x.id)+'">Done</button></div>':'')+'</div>'}).join(''):'<div class="empty">Нічого немає</div>';}
function bindItemButtons(root){root.querySelectorAll('[data-done]').forEach(function(b){b.addEventListener('click',function(){done(b.dataset.done)})});}
async function done(id){await api('/api/items/'+encodeURIComponent(id),{method:'PUT',body:JSON.stringify({status:'done'})});toast('Готово');loadItems();loadToday();}
function v(id){return document.getElementById(id).value} function esc(s){return String(s||'').replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
document.addEventListener('keydown',function(e){if(e.key==='Enter'&&document.getElementById('login')&&document.getElementById('login').classList.contains('active'))login()});
boot();
</script>
</body></html>`;
}
